SITE = {
    "name": "B Tecnologia",
    "site_url": "https://brunoluizmendes.github.io",
    "headline_en": "Data and automation that don't call you at 3am.",
    "headline_pt": "Dados e automacao que nao te ligam de madrugada.",
    "subheadline_en": (
        "Pipelines, integrations, and AI agents in production, with logs, retries, and monitoring "
        "from day one, so you find out something broke before your customer does."
    ),
    "subheadline_pt": (
        "Pipelines, integracoes e agentes de AI em producao, com logs, retries e monitoramento desde "
        "o primeiro deploy, para voce descobrir que algo quebrou antes do seu cliente."
    ),
    "role_en": "Data Engineering + AI Systems",
    "role_pt": "Data Engineering + Sistemas de AI",
    "location_en": "Built for finance, ops, marketing, and growth teams.",
    "location_pt": "Feito para times de financas, operacoes, marketing e growth.",
    "github_url": "https://github.com/brunoluizmendes",
    "linkedin_url": "https://www.linkedin.com/in/brunoluizmendes/",
    "upwork_url": "https://www.upwork.com/freelancers/~015610c5abb8e28a49?mp_source=share",
    "calendly_url": "https://calendly.com/brunoluizmendes",
    "logo_alt": "B Tecnologia brand mark",
    "palette": {
        "primary": "#4F62E3",
        "secondary": "#12173A",
        "background": "#E7E7E7",
        "neutral": "#C3C2C3",
    },
    "stats": [
        {
            "value": "+30",
            "label_en": "clients served",
            "label_pt": "clientes atendidos",
        },
        {
            "value": "GCP + AWS",
            "label_en": "delivery across cloud, warehouse, and activation stacks",
            "label_pt": "entrega em cloud, warehouse e stacks de ativacao",
        },
    ],
    "proof_ribbon": [
        "Python",
        "dbt",
        "BigQuery",
        "AWS",
        "GCP",
        "Lakehouse",
        "Dagster",
        "Observability",
        "AI Agents",
        "Workflow Automation",
        "Revenue Ops",
        "ERP Integration",
        "Finance Automation",
        "Marketing Attribution",
        "CRM Automation",
        "GitHub Actions",
    ],
    "services": [
        {
            "icon": "database",
            "title_en": "Data platforms and lakehouses",
            "title_pt": "Plataformas de dados e lakehouses",
            "body_en": "A warehouse that doesn't need someone poking it every week to stay up.",
            "body_pt": "Warehouse que nao precisa de alguem cutucando toda semana pra continuar de pe.",
        },
        {
            "icon": "target",
            "title_en": "Marketing and revenue integrations",
            "title_pt": "Integracoes de marketing e receita",
            "body_en": "Know which channel actually brought the customer, without stitching Meta Ads, GA4, and CRM together by hand to find out.",
            "body_pt": "Saiba qual canal trouxe o cliente, sem juntar Meta Ads, GA4 e CRM na mao pra descobrir.",
        },
        {
            "icon": "wallet",
            "title_en": "Finance and ops automation",
            "title_pt": "Automacao financeira e operacional",
            "body_en": "No more reconciliation spreadsheet only one person knows how to open. ERP and finance talking directly.",
            "body_pt": "Chega de planilha de conciliacao que so uma pessoa sabe abrir. ERP e financeiro conversando direto.",
        },
        {
            "icon": "bot",
            "title_en": "AI workflows and signal pipelines",
            "title_pt": "Fluxos de AI e pipelines de sinais",
            "body_en": "An AI agent you can actually audit when something goes wrong, not a black box nobody wants to debug.",
            "body_pt": "Agente de AI que voce consegue auditar quando algo da errado, nao uma caixa preta que ninguem quer debugar.",
        },
    ],
    "process": [
        {
            "icon": "search",
            "step": "01",
            "title_en": "Scope",
            "title_pt": "Escopo",
            "body_en": "A short discovery pass finds the few decisions that actually drive cost and architecture, not a 40-slide deck.",
            "body_pt": "Uma etapa curta de discovery acha as poucas decisoes que realmente definem custo e arquitetura, nao uma apresentacao de 40 slides.",
        },
        {
            "icon": "terminal",
            "step": "02",
            "title_en": "Build",
            "title_pt": "Construcao",
            "body_en": "You see the pipeline running against real data in the first weeks, not just moving on a sprint board.",
            "body_pt": "Voce ve o pipeline rodando com dado real nas primeiras semanas, nao so andando num board de sprint.",
        },
        {
            "icon": "shield-check",
            "step": "03",
            "title_en": "Operate",
            "title_pt": "Operacao",
            "body_en": "Every pipeline ships with monitoring and safe retry paths, not bolted on after an incident.",
            "body_pt": "Todo pipeline sai com monitoramento e retries seguros, sem depender de correcao pos-incidente.",
        },
        {
            "icon": "package-check",
            "step": "04",
            "title_en": "Hand off",
            "title_pt": "Entrega",
            "body_en": "Runbooks and a repo structured so another engineer can extend it without a walkthrough call.",
            "body_pt": "Runbooks e um repositorio organizados para outro engenheiro evoluir sem precisar de uma call explicando tudo.",
        },
    ],
    "about_en": (
        "Senior-only engineering delivery, direct communication, and systems built to outlast the first six months."
    ),
    "about_pt": (
        "Entrega de engenharia 100% senior, comunicacao direta, e sistemas feitos para durar mais que os primeiros seis meses."
    ),
}

LANES = [
    {
        "key": "platform",
        "title_en": "Platform, Warehouse, and Orchestration",
        "title_pt": "Plataforma, Warehouse e Orquestracao",
        "body_en": "Core analytics foundations, performance, and orchestration-first delivery.",
        "body_pt": "Fundacao de analytics, performance e entrega orientada a orquestracao.",
    },
    {
        "key": "finance",
        "title_en": "Finance and Operations Automation",
        "title_pt": "Automacao de Financas e Operacoes",
        "body_en": "Pipelines and automations for ERP, finance workflows, and process control.",
        "body_pt": "Pipelines e automacoes para ERP, fluxos financeiros e controle operacional.",
    },
    {
        "key": "marketing",
        "title_en": "Marketing, Attribution, and Growth Data",
        "title_pt": "Marketing, Atribuicao e Dados de Growth",
        "body_en": "Attribution-ready pipelines for ads, analytics, mobile, and conversion reporting.",
        "body_pt": "Pipelines prontos para atribuicao em ads, analytics, mobile e conversao.",
    },
    {
        "key": "automation",
        "title_en": "Signals and AI Automation",
        "title_pt": "Sinais e AI Automation",
        "body_en": "Trend detection and agent-driven operations with engineering-grade controls.",
        "body_pt": "Trend detection e operacoes com agentes, com controles de engenharia.",
    },
]

PROJECTS = [
    {
        "slug": "financial-process-automation-scraping",
        "repo": "financial-process-automation-scraping",
        "lane": "finance",
        "title": "Financial Process Automation via Web Scraping",
        "category_en": "Finance automation",
        "category_pt": "Automacao financeira",
        "tagline_en": "Stop copying invoices and statements by hand from portals that don't have an API.",
        "tagline_pt": "Pare de copiar nota e extrato na mao de portal que nao tem API.",
        "summary_en": "A Python scraping flow that logs in, reconciles what it finds, and hands finance clean, BigQuery-ready records instead of a spreadsheet full of manual entries.",
        "summary_pt": "Um fluxo em Python que faz login, concilia o que encontra e entrega pro financeiro registros limpos, prontos para BigQuery, em vez de uma planilha cheia de lancamento manual.",
        "problem_en": "Finance teams still copy invoices, statements, payment status, and tax records from browser-only portals.",
        "problem_pt": "Times financeiros ainda copiam notas, extratos, status de pagamento e impostos de portais web.",
        "solution_en": "Automated logins handle the scraping, while reconciliation checks, fallback logic, and retries catch what a script alone would miss.",
        "solution_pt": "Logins automatizados cuidam do scraping, enquanto conciliacao, fallback e retries cobrem o que um script sozinho deixaria passar.",
        "outcome_en": "Finance stops re-typing numbers by hand, and every downstream report stays auditable and safe to replay.",
        "outcome_pt": "O time financeiro para de retrabalhar numeros na mao, e todo relatorio downstream continua auditavel e seguro para replay.",
        "stack": ["Python", "Browser automation", "dbt", "BigQuery", "Queue/outbox", "Structured logs"],
        "deliverables_en": [
            "Authenticated scraping flow",
            "Reconciliation checks before publish",
            "Ops dataset logs and dead-letter handling",
            "Warehouse-ready finance models",
        ],
        "deliverables_pt": [
            "Fluxo de scraping autenticado",
            "Conciliacao antes do publish",
            "Logs operacionais e dead-letter",
            "Modelos financeiros prontos para warehouse",
        ],
    },
    {
        "slug": "erp-to-bigquery-finance-analytics",
        "repo": "erp-to-bigquery-finance-analytics",
        "lane": "finance",
        "title": "General ERP Data Pipeline",
        "category_en": "ERP integration",
        "category_pt": "Integracao ERP",
        "tagline_en": "Finance stops fighting inconsistent ERP exports, even with more than one system in the mix.",
        "tagline_pt": "Financeiro para de brigar com export de ERP inconsistente, mesmo com mais de um sistema no meio.",
        "summary_en": "dbt layers turn whatever each ERP exports into one canonical model, with reconciliation and incremental loads that survive a messy backfill.",
        "summary_pt": "Camadas dbt transformam o que cada ERP exporta em um modelo canonico unico, com conciliacao e cargas incrementais que sobrevivem a um backfill confuso.",
        "problem_en": "Growing teams often run finance reporting across inconsistent ERP exports and broken joins.",
        "problem_pt": "Times em crescimento frequentemente fazem reporting financeiro sobre exports inconsistentes de ERP.",
        "solution_en": "dbt layers translate whatever the ERP exports into one canonical model, with validation queries catching mismatches before they reach a dashboard.",
        "solution_pt": "Camadas dbt traduzem o que o ERP exporta para um modelo canonico unico, com queries de validacao pegando divergencias antes do dashboard.",
        "outcome_en": "Finance gets a reporting foundation it can trust today, with no need to replatform the ERP first.",
        "outcome_pt": "Financas ganha uma base de reporting confiavel hoje, sem precisar trocar o ERP antes.",
        "stack": ["Python", "dbt", "BigQuery", "Canonical modeling", "Ops layer", "Terraform"],
        "deliverables_en": [
            "Canonical ERP staging and marts",
            "Reconciliation logic for balances and payments",
            "Backfill-safe incremental loading",
            "Operational runbooks and dashboards",
        ],
        "deliverables_pt": [
            "Camadas canonicas de ERP",
            "Logica de conciliacao para saldo e pagamentos",
            "Carga incremental segura para backfill",
            "Runbooks e visibilidade operacional",
        ],
    },
    {
        "slug": "gcp-lakehouse-dbt-bigquery",
        "repo": "gcp-lakehouse-dbt-bigquery",
        "lane": "platform",
        "title": "GCP Lakehouse Implementation",
        "category_en": "Lakehouse on GCP",
        "category_pt": "Lakehouse na GCP",
        "tagline_en": "Analytics on GCP that your team can actually maintain, not a platform that outgrows you.",
        "tagline_pt": "Analytics na GCP que o seu time consegue manter, nao uma plataforma maior do que a operacao precisa.",
        "summary_en": "Raw, stage, and analytics layers on GCS and BigQuery, built with cost controls so a spike in usage doesn't turn into a surprise bill.",
        "summary_pt": "Camadas raw, stage e analytics sobre GCS e BigQuery, com controle de custo para um pico de uso nao virar surpresa na fatura.",
        "problem_en": "Teams want dependable analytics operations on GCP without taking on a huge platform surface area.",
        "problem_pt": "Times querem analytics confiavel na GCP sem assumir uma plataforma gigante e cara de manter.",
        "solution_en": "Raw, stage, and analytics layers sit on GCS and BigQuery with incremental-safe loading and their own observability tables.",
        "solution_pt": "Camadas raw, stage e analytics ficam sobre GCS e BigQuery com carga incremental segura e tabelas proprias de observabilidade.",
        "outcome_en": "BI and activation use cases run on infrastructure the team can actually maintain, not a platform that outgrows them.",
        "outcome_pt": "BI e ativacao rodam sobre uma infraestrutura que o time consegue manter, nao uma plataforma maior do que a operacao precisa.",
        "stack": ["Python", "dbt", "GCS", "BigQuery", "Cloud Scheduler", "Terraform"],
        "deliverables_en": [
            "Layered lakehouse design",
            "Incremental and backfill-safe ingestion",
            "BigQuery cost/performance controls",
            "Ops datasets for runs and failures",
        ],
        "deliverables_pt": [
            "Lakehouse em camadas",
            "Ingestao incremental e segura para backfill",
            "Controles de custo/performance no BigQuery",
            "Datasets operacionais para runs e falhas",
        ],
    },
    {
        "slug": "aws-lakehouse-medallion",
        "repo": "aws-lakehouse-medallion",
        "lane": "platform",
        "title": "AWS Lakehouse Implementation",
        "category_en": "Lakehouse on AWS",
        "category_pt": "Lakehouse na AWS",
        "tagline_en": "A lakehouse on AWS that holds up when an auditor actually asks how the data got there.",
        "tagline_pt": "Um lakehouse na AWS que resiste quando um auditor pergunta de verdade como o dado chegou ali.",
        "summary_en": "Bronze, silver, and gold layers on S3, with IAM/KMS governance built in from day one instead of bolted on after a security review flags it.",
        "summary_pt": "Camadas bronze, silver e gold no S3, com governanca IAM/KMS desde o inicio, em vez de remendada depois que uma revisao de seguranca aponta o problema.",
        "problem_en": "AWS-first teams need lakehouse clarity without ending up with expensive, unclear data sprawl.",
        "problem_pt": "Times AWS-first precisam de clareza de lakehouse sem cair em data sprawl caro e confuso.",
        "solution_en": "Bronze, silver, and gold layers on S3 come with IAM/KMS governance and operational SLAs wired in from day one, not layered on after launch.",
        "solution_pt": "Camadas bronze, silver e gold no S3 chegam com governanca IAM/KMS e SLA operacional ja embutidos desde o inicio, nao adicionados depois do lancamento.",
        "outcome_en": "AWS-first teams get an analytics foundation that holds up under audit and is straightforward to extend.",
        "outcome_pt": "Times AWS-first ganham uma base analitica que resiste a auditoria e e simples de evoluir.",
        "stack": ["Python", "dbt", "S3", "Glue Catalog", "CloudWatch", "Terraform"],
        "deliverables_en": [
            "Bronze, silver, and gold dataset flow",
            "Governance and encryption baseline",
            "Cost and performance optimization layer",
            "BI-ready curated marts",
        ],
        "deliverables_pt": [
            "Fluxo bronze, silver e gold",
            "Base de governanca e criptografia",
            "Camada de custo e performance",
            "Marts curados prontos para BI",
        ],
    },
    {
        "slug": "dagster-dbt-orchestration-pipeline",
        "repo": "dagster-dbt-orchestration-pipeline",
        "lane": "platform",
        "title": "Dagster + dbt Orchestration Pipeline",
        "category_en": "Orchestration",
        "category_pt": "Orquestracao",
        "tagline_en": "Orchestration a second engineer can read, not a cron job only one person understands.",
        "tagline_pt": "Orquestracao que um segundo engenheiro consegue ler, nao um cron job que so uma pessoa entende.",
        "summary_en": "Asset boundaries and dbt transforms replace cron-script guesswork, with replay-safe runs so a failed job doesn't mean redoing everything by hand.",
        "summary_pt": "Fronteiras de assets e transforms em dbt substituem o cron script no escuro, com execucao segura para replay, para um job falho nao significar refazer tudo na mao.",
        "problem_en": "Data teams often need more orchestration clarity than cron scripts but less complexity than overbuilt platform tooling.",
        "problem_pt": "Times de dados precisam de mais clareza que cron scripts, mas menos complexidade que plataformas superdimensionadas.",
        "solution_en": "Asset boundaries, dbt transforms, and event logs replace cron-script guesswork with something a second engineer can actually read.",
        "solution_pt": "Fronteiras de assets, transforms em dbt e event logs substituem o cron script por algo que um segundo engenheiro consegue ler de fato.",
        "outcome_en": "Orchestration becomes legible to teams outside the platform group, without losing the rigor of a production system.",
        "outcome_pt": "A orquestracao fica legivel para times fora do grupo de plataforma, sem perder o rigor de um sistema de producao.",
        "stack": ["Python", "Dagster-style assets", "dbt", "DuckDB", "Ops logs", "Terraform"],
        "deliverables_en": [
            "Asset-oriented orchestration structure",
            "dbt transformation layer",
            "Event logs and dead-letter flow",
            "Replay-safe publish behavior",
        ],
        "deliverables_pt": [
            "Estrutura orientada a assets",
            "Camada dbt de transformacao",
            "Event logs e dead-letter",
            "Publish seguro para replay",
        ],
    },
    {
        "slug": "bigquery-query-optimization-workload",
        "repo": "bigquery-query-optimization-workload",
        "lane": "platform",
        "title": "BigQuery Query Optimization Workload",
        "category_en": "BigQuery optimization",
        "category_pt": "Otimizacao BigQuery",
        "tagline_en": "Find out which query is inflating your BigQuery bill before finance asks.",
        "tagline_pt": "Descubra qual query esta inflando a fatura do BigQuery antes que o financeiro pergunte.",
        "summary_en": "Turns BigQuery job telemetry into a ranked backlog, so tuning work has a clear next target and an expected savings number attached.",
        "summary_pt": "Transforma a telemetria de jobs do BigQuery em um backlog priorizado, para o trabalho de tuning ter um proximo alvo claro e uma economia esperada associada.",
        "problem_en": "BigQuery cost spikes usually appear before teams can explain which jobs, dashboards, or query patterns are driving waste.",
        "problem_pt": "Picos de custo no BigQuery geralmente aparecem antes de o time conseguir explicar quais jobs, dashboards ou padroes de query estao desperdicando recursos.",
        "solution_en": "A pipeline that validates BigQuery job metadata, models optimization opportunities, and publishes a monitoring-ready backlog for tuning work.",
        "solution_pt": "Um pipeline que valida metadados de jobs do BigQuery, modela oportunidades de otimizacao e publica um backlog pronto para monitoramento.",
        "outcome_en": "Makes warehouse cost and performance work visible, prioritized, and easier to justify to stakeholders.",
        "outcome_pt": "Deixa o trabalho de custo e performance de warehouse visivel, priorizado e mais facil de justificar para o negocio.",
        "stack": ["Python", "BigQuery INFORMATION_SCHEMA", "dbt", "Cost monitoring", "Job observability", "Terraform"],
        "deliverables_en": [
            "BigQuery jobs and cost telemetry flow",
            "Optimization scoring and ranking layer",
            "Monitoring-ready backlog of tuning candidates",
            "Sample BigQuery query optimization patterns",
        ],
        "deliverables_pt": [
            "Fluxo de telemetria de jobs e custos do BigQuery",
            "Camada de scoring e ranking para otimizacao",
            "Backlog pronto para monitoramento de tuning",
            "Exemplos de otimizacao de queries no BigQuery",
        ],
    },
    {
        "slug": "meta-ads-to-bigquery-pipeline",
        "repo": "meta-ads-to-bigquery-pipeline",
        "lane": "marketing",
        "title": "Meta Ads Data Pipeline",
        "category_en": "Paid media integration",
        "category_pt": "Integracao de midia paga",
        "tagline_en": "Paid media numbers that hold up hour over hour, without someone patching a spreadsheet.",
        "tagline_pt": "Numero de midia paga que se mantem hora a hora, sem ninguem remendando planilha.",
        "summary_en": "Campaign, spend, click, lead, and conversion data synced idempotently, so a duplicate row doesn't quietly inflate the numbers marketing reports on.",
        "summary_pt": "Campanha, spend, clique, lead e conversao sincronizados de forma idempotente, para uma linha duplicada nao inflar em silencio o numero que o marketing reporta.",
        "problem_en": "Paid media teams need clean marketing data fast, but hourly syncs often duplicate, drift, or break silently.",
        "problem_pt": "Times de midia paga precisam de dados limpos rapido, mas sincronizacoes por hora costumam duplicar ou quebrar.",
        "solution_en": "Idempotent syncs and UTM normalization stop duplicate rows before they happen, with validation queries flagging anything that still looks off.",
        "solution_pt": "Syncs idempotentes e normalizacao de UTM evitam a duplicidade antes que ela aconteca, com queries de validacao sinalizando o que ainda parecer estranho.",
        "outcome_en": "Paid media reporting holds up hour over hour, and nobody has to open a spreadsheet to patch it.",
        "outcome_pt": "O reporting de midia paga se mantem consistente hora a hora, sem ninguem precisar abrir planilha para remendar.",
        "stack": ["Python", "Meta Ads", "dbt", "BigQuery", "Outbox", "GitHub Actions"],
        "deliverables_en": [
            "Raw-to-analytics paid media modeling",
            "UTM normalization and attribution support",
            "Retry-safe publish and dead-letter flow",
            "Hourly operational observability",
        ],
        "deliverables_pt": [
            "Modelagem raw-to-analytics de midia paga",
            "Normalizacao de UTM e suporte a atribuicao",
            "Publish seguro com retries e dead-letter",
            "Observabilidade operacional horaria",
        ],
    },
    {
        "slug": "appsflyer-to-bigquery-integration",
        "repo": "appsflyer-to-bigquery-integration",
        "lane": "marketing",
        "title": "AppsFlyer to BigQuery Integration",
        "category_en": "Mobile attribution",
        "category_pt": "Atribuicao mobile",
        "tagline_en": "Mobile attribution you can act on, not a feed everyone double-checks before trusting.",
        "tagline_pt": "Atribuicao mobile que voce usa pra agir, nao um feed que todo mundo confere de novo antes de confiar.",
        "summary_en": "Installs, in-app events, and campaign costs normalized through a path built for mobile's specific quirks, so growth stops reconciling numbers by hand.",
        "summary_pt": "Installs, eventos in-app e custo de campanha normalizados por um caminho pensado pras particularidades de mobile, para growth parar de conciliar numero na mao.",
        "problem_en": "Mobile acquisition data is valuable, but attribution feeds often arrive fragmented and hard to trust.",
        "problem_pt": "Dados de aquisicao mobile sao valiosos, mas os feeds de atribuicao chegam fragmentados e dificeis de confiar.",
        "solution_en": "Installs, in-app events, and campaign costs get normalized through a Python + dbt path built for mobile-specific quirks, not adapted from a generic ETL.",
        "solution_pt": "Installs, eventos in-app e custos de campanha sao normalizados por um caminho Python + dbt pensado para as particularidades de mobile, nao adaptado de um ETL generico.",
        "outcome_en": "Mobile attribution reporting becomes something growth can act on, not just a dataset to double-check.",
        "outcome_pt": "O reporting de atribuicao mobile passa a ser algo que growth usa para agir, nao apenas um dataset para checar de novo.",
        "stack": ["Python", "AppsFlyer", "dbt", "BigQuery", "Attribution modeling", "Ops logs"],
        "deliverables_en": [
            "Install and event normalization",
            "Campaign cost reconciliation",
            "Analytics-ready attribution marts",
            "Replay-safe publish flow",
        ],
        "deliverables_pt": [
            "Normalizacao de installs e eventos",
            "Conciliacao de custo de campanha",
            "Marts de atribuicao prontos para analytics",
            "Fluxo de publish seguro para replay",
        ],
    },
    {
        "slug": "ga4-to-bigquery-integration",
        "repo": "ga4-to-bigquery-integration",
        "lane": "marketing",
        "title": "GA4 to BigQuery Integration",
        "category_en": "Web analytics integration",
        "category_pt": "Integracao de web analytics",
        "tagline_en": "A GA4 export your team can build channel reporting on, instead of a raw dump nobody quite trusts.",
        "tagline_pt": "Um export do GA4 que o seu time usa pra montar reporting por canal, em vez de um dump bruto que ninguem confia de verdade.",
        "summary_en": "Sessions, conversions, and traffic-source data normalized into stable models, with logs clean enough to survive a finance or growth review.",
        "summary_pt": "Sessoes, conversoes e origem de trafego normalizados em modelos estaveis, com logs limpos o suficiente para sobreviver a uma revisao de financas ou growth.",
        "problem_en": "GA4 exports are useful but messy when teams need stable warehouse models and channel reporting.",
        "problem_pt": "Exports do GA4 sao uteis, mas ficam confusos quando o time precisa de modelos estaveis e reporting por canal.",
        "solution_en": "Sessions, conversions, and traffic-source data get normalized into stable models, with ops logs auditable enough for a finance or growth review.",
        "solution_pt": "Sessoes, conversoes e dados de origem de trafego sao normalizados em modelos estaveis, com logs operacionais auditaveis o suficiente para uma revisao de financas ou growth.",
        "outcome_en": "GA4 becomes a source teams can build channel reporting on, instead of a raw export everyone quietly distrusts.",
        "outcome_pt": "O GA4 passa a ser uma fonte para construir reporting por canal, em vez de um export bruto em que todo mundo desconfia por baixo dos panos.",
        "stack": ["Python", "GA4", "dbt", "BigQuery", "Traffic source marts", "Ops logs"],
        "deliverables_en": [
            "Normalized sessions and conversions",
            "Traffic-source reporting layer",
            "Warehouse-ready analytics marts",
            "Replay and dead-letter controls",
        ],
        "deliverables_pt": [
            "Sessoes e conversoes normalizadas",
            "Camada de reporting por origem de trafego",
            "Marts prontos para warehouse",
            "Controles de replay e dead-letter",
        ],
    },
    {
        "slug": "trend-detection-signal-pipeline",
        "repo": "trend-detection-signal-pipeline",
        "lane": "automation",
        "title": "Trend Detection Signal Pipeline",
        "category_en": "Signal intelligence",
        "category_pt": "Signal intelligence",
        "tagline_en": "One ranked view of what's rising, instead of five open tabs and a gut feeling.",
        "tagline_pt": "Uma unica visao ranqueada do que esta em alta, em vez de cinco abas abertas e um chute.",
        "summary_en": "News, social, and search feeds pulled into one scoring layer, so a rising topic shows up with a number attached instead of someone's hunch.",
        "summary_pt": "Feeds de news, social e search unificados em uma camada de scoring, para um topico em alta aparecer com um numero associado, em vez do palpite de alguem.",
        "problem_en": "Trend work is usually scattered across feeds, social dashboards, and search tools with no central scoring logic.",
        "problem_pt": "Trend work costuma ficar espalhado entre feeds, dashboards sociais e ferramentas de busca sem score central.",
        "solution_en": "News, social, and search feeds get pulled into one normalized scoring layer, so rising topics surface with a number attached instead of a gut feeling.",
        "solution_pt": "Feeds de news, social e search sao unificados em uma camada de scoring normalizado, para que topicos em alta aparecam com um numero associado, e nao so uma sensacao.",
        "outcome_en": "Content, growth, or research teams get one ranked view of momentum instead of five open tabs.",
        "outcome_pt": "Times de content, growth ou research passam a ter uma unica visao ranqueada de momentum, em vez de cinco abas abertas.",
        "stack": ["Python", "Signal scoring", "dbt", "DuckDB", "Alert-ready outputs", "Observability"],
        "deliverables_en": [
            "News, social, and search ingestion model",
            "Normalized scoring layer",
            "Trend-ranking analytics mart",
            "Alert-ready publish output",
        ],
        "deliverables_pt": [
            "Modelo de ingestao de news, social e search",
            "Camada de scoring normalizado",
            "Mart analitico de ranking de trends",
            "Saida pronta para alertas",
        ],
    },
    {
        "slug": "ai-automation-engineer-workflows",
        "repo": "ai-automation-engineer-workflows",
        "lane": "automation",
        "title": "AI Automation Engineer Workflows",
        "category_en": "AI operations",
        "category_pt": "Operacoes com AI",
        "tagline_en": "An AI automation that survives contact with routing, retries, and someone asking why it did that.",
        "tagline_pt": "Uma automacao com AI que sobrevive a roteamento, retries e alguem perguntando por que ela fez isso.",
        "summary_en": "Inbox ingestion, CRM task logic, and agent action records give every automated decision a paper trail someone can actually audit, instead of a fragile prompt chain.",
        "summary_pt": "Ingestao de inbox, logica de tarefas em CRM e registros de acao do agente dao a cada decisao automatizada um rastro auditavel, em vez de uma cadeia fragil de prompts.",
        "problem_en": "Many AI automations look impressive in demos but fail once routing, retries, and business accountability matter.",
        "problem_pt": "Muitas automacoes com AI impressionam em demo, mas falham quando roteamento, retries e accountability importam.",
        "solution_en": "Inbox ingestion, CRM task logic, and agent action records give every automated decision a paper trail someone can actually audit.",
        "solution_pt": "Ingestao de inbox, logica de tarefas em CRM e registros de acoes do agente dao a cada decisao automatizada um rastro que alguem consegue auditar.",
        "outcome_en": "AI automation stops being a fragile prompt chain and starts behaving like a system ops can own.",
        "outcome_pt": "A automacao com AI deixa de ser uma cadeia fragil de prompts e passa a se comportar como um sistema que a operacao consegue sustentar.",
        "stack": ["Python", "AI workflow patterns", "CRM automation", "dbt", "Event logs", "Outbox"],
        "deliverables_en": [
            "Email and task routing pipeline",
            "Agent action contracts",
            "CRM automation model",
            "Audit-friendly operational telemetry",
        ],
        "deliverables_pt": [
            "Pipeline de roteamento de emails e tarefas",
            "Contratos para acoes do agente",
            "Modelo de automacao em CRM",
            "Telemetria operacional auditavel",
        ],
    },
]
